const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const demo=[
{id:'1',action:'Mapear demandas educacionais',delivery:'Diagnóstico consolidado das unidades',date:'2027-01-28',owner:'Equipe NEAM',status:'Concluída',priority:'Alta',progress:100},
{id:'2',action:'Planejar formação continuada',delivery:'Plano formativo e calendário anual',date:'2027-02-19',owner:'Coordenação Pedagógica',status:'Em andamento',priority:'Alta',progress:65},
{id:'3',action:'Realizar encontro com gestores',delivery:'Ata, registros e encaminhamentos',date:'2027-03-12',owner:'Equipe SEMED',status:'Planejada',priority:'Média',progress:20},
{id:'4',action:'Monitorar indicadores escolares',delivery:'Relatório bimestral de aprendizagem',date:'2027-04-30',owner:'Equipe NEAM',status:'Planejada',priority:'Alta',progress:10},
{id:'5',action:'Produzir materiais de apoio',delivery:'Kit pedagógico para as escolas',date:'2027-05-21',owner:'Coordenação Pedagógica',status:'Planejada',priority:'Média',progress:5},
{id:'6',action:'Avaliar execução do semestre',delivery:'Relatório de avaliação e plano corretivo',date:'2027-06-25',owner:'Equipe SEMED',status:'Planejada',priority:'Alta',progress:0}];
let data=JSON.parse(localStorage.getItem('bodoco-plan-2027')||'null')||demo;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monthOf=d=>months[Number(d.slice(5,7))-1]||''; const statusClass=s=>s.replaceAll(' ','-');
function save(){localStorage.setItem('bodoco-plan-2027',JSON.stringify(data))}
function filtered(){const m=$('#fMonth').value,s=$('#fStatus').value,o=$('#fOwner').value,p=$('#fPriority').value,q=$('#fSearch').value.toLowerCase();return data.filter(x=>(!m||monthOf(x.date)===m)&&(!s||x.status===s)&&(!o||x.owner===o)&&(!p||x.priority===p)&&(!q||[x.action,x.delivery,x.owner].join(' ').toLowerCase().includes(q)))}
function badge(s){return '<span class="badge '+statusClass(s)+'">'+esc(s)+'</span>'}
function populateFilters(){const current=$('#fOwner').value;$('#fMonth').innerHTML='<option value="">Todos</option>'+months.map(m=>'<option>'+m+'</option>').join('');const owners=[...new Set(data.map(x=>x.owner))].sort();$('#fOwner').innerHTML='<option value="">Todos</option>'+owners.map(o=>'<option>'+esc(o)+'</option>').join('');if(owners.includes(current))$('#fOwner').value=current}
function render(){const d=filtered(),count=s=>d.filter(x=>x.status===s).length,total=d.length,done=count('Concluída');$('#kTotal').textContent=total;$('#kDone').textContent=done;$('#kDonePct').textContent=(total?Math.round(done/total*100):0)+'% do total';$('#kDoing').textContent=count('Em andamento');$('#kLate').textContent=count('Atrasada');$('#kProgress').textContent=(total?Math.round(d.reduce((a,x)=>a+Number(x.progress),0)/total):0)+'%';renderMonthChart(d);renderDonut(d);renderAttention(d);renderOwners(d);renderMonths(d);renderAll(d)}
function renderMonthChart(d){$('#monthChart').innerHTML=months.map((m,i)=>{const a=d.filter(x=>monthOf(x.date)===m),done=a.filter(x=>x.status==='Concluída').length,other=a.length-done,max=Math.max(1,...months.map(mm=>d.filter(x=>monthOf(x.date)===mm).length));return '<div class="bar-wrap" title="'+m+': '+a.length+' ações"><div class="bar" style="height:'+(done/max*100)+'%;background:#27d17f"></div><div class="bar" style="height:'+(other/max*100)+'%;background:#3679aa"></div><span class="bar-label">'+m.slice(0,3)+'</span></div>'}).join('')}
function renderDonut(d){const statuses=['Concluída','Em andamento','Atrasada','Planejada','Cancelada'],colors=['#27d17f','#66b3ff','#ff6b6b','#ffc857','#bd7ab3'];let start=0,parts=[];statuses.forEach((s,i)=>{let pct=d.length?d.filter(x=>x.status===s).length/d.length*100:0;parts.push(colors[i]+' '+start+'% '+(start+pct)+'%');start+=pct});$('#donut').style.background=d.length?'conic-gradient('+parts.join(',')+')':'#1a3628';$('#donutValue').textContent=d.length;$('#statusList').innerHTML=statuses.map((s,i)=>'<div class="status-row"><span><i class="dot" style="background:'+colors[i]+'"></i>'+s+'</span><b>'+d.filter(x=>x.status===s).length+'</b></div>').join('')}
function renderAttention(d){const a=[...d].filter(x=>x.status!=='Concluída'&&x.status!=='Cancelada').sort((x,y)=>x.date.localeCompare(y.date)).slice(0,8);$('#attentionRows').innerHTML=a.length?a.map(x=>'<tr><td><b>'+esc(x.action)+'</b><br><small style="color:var(--muted)">'+esc(x.delivery)+'</small></td><td>'+esc(x.owner)+'</td><td>'+new Date(x.date+'T12:00').toLocaleDateString('pt-BR')+'</td><td>'+badge(x.status)+'</td><td><div class="progress"><i style="width:'+x.progress+'%"></i></div><small>'+x.progress+'%</small></td></tr>').join(''):'<tr><td colspan="5" class="empty">Nenhuma entrega no recorte selecionado.</td></tr>'}
function renderOwners(d){const owners=[...new Set(d.map(x=>x.owner))].map(o=>({o,n:d.filter(x=>x.owner===o).length})).sort((a,b)=>b.n-a.n),max=Math.max(1,...owners.map(x=>x.n));$('#ownerBars').innerHTML=owners.length?owners.map(x=>'<div style="margin:15px 0"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:6px"><b>'+esc(x.o)+'</b><span>'+x.n+' ações</span></div><div class="progress"><i style="width:'+(x.n/max*100)+'%"></i></div></div>').join(''):'<div class="empty">Sem responsáveis no recorte.</div>'}
function renderMonths(d){$('#monthGrid').innerHTML=months.map(m=>{const rows=d.filter(x=>monthOf(x.date)===m).sort((a,b)=>a.date.localeCompare(b.date));return '<div class="month"><div class="month-title">'+m+'</div><table><thead><tr><th>Ação</th><th>Entrega</th><th>Data</th></tr></thead><tbody>'+(rows.length?rows.map(x=>'<tr><td>'+esc(x.action)+'</td><td>'+esc(x.delivery)+'</td><td>'+x.date.slice(8,10)+'/ '+badge(x.status)+'</td></tr>').join(''):'<tr><td colspan="3" class="empty">Sem ações</td></tr>')+'</tbody></table></div>'}).join('')}
function renderAll(d){$('#allRows').innerHTML=d.length?d.map(x=>'<tr><td><b>'+esc(x.action)+'</b></td><td>'+esc(x.delivery)+'</td><td>'+monthOf(x.date)+'</td><td>'+new Date(x.date+'T12:00').toLocaleDateString('pt-BR')+'</td><td>'+esc(x.owner)+'</td><td>'+badge(x.status)+'</td><td>'+x.priority+'</td><td>'+x.progress+'%</td><td><button class="btn" onclick="editItem(''+x.id+'')">Editar</button> <button class="btn danger" onclick="removeItem(''+x.id+'')">Excluir</button></td></tr>').join(''):'<tr><td colspan="9" class="empty">A base está vazia.</td></tr>'}
function showToast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2200)}
function openModal(item){$('#modalTitle').textContent=item?'Editar ação':'Nova ação';$('#editId').value=item?.id||'';$('#action').value=item?.action||'';$('#delivery').value=item?.delivery||'';$('#date').value=item?.date||'2027-01-15';$('#owner').value=item?.owner||'';$('#status').value=item?.status||'Planejada';$('#priority').value=item?.priority||'Média';$('#progress').value=item?.progress||0;$('#progressLabel').textContent=$('#progress').value+'%';$('#modalBg').style.display='flex'}
window.editItem=id=>openModal(data.find(x=>x.id===id));window.removeItem=id=>{if(confirm('Excluir esta ação?')){data=data.filter(x=>x.id!==id);save();populateFilters();render();showToast('Ação excluída')}};
$('#actionForm').onsubmit=e=>{e.preventDefault();const item={id:$('#editId').value||Date.now().toString(),action:$('#action').value.trim(),delivery:$('#delivery').value.trim(),date:$('#date').value,owner:$('#owner').value.trim(),status:$('#status').value,priority:$('#priority').value,progress:Number($('#progress').value)};if($('#editId').value)data=data.map(x=>x.id===item.id?item:x);else data.push(item);save();$('#modalBg').style.display='none';populateFilters();render();showToast('Ação salva com sucesso')};
$('#newBtn').onclick=()=>openModal();$('#cancelBtn').onclick=()=>$('#modalBg').style.display='none';$('#modalBg').onclick=e=>{if(e.target===$('#modalBg'))$('#modalBg').style.display='none'};$('#progress').oninput=e=>$('#progressLabel').textContent=e.target.value+'%';
$$('.filters select,.filters input').forEach(x=>x.addEventListener('input',render));$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.section).classList.add('active')});
$('#clearBtn').onclick=()=>{if(confirm('Limpar toda a base? Esta ação não pode ser desfeita.')){data=[];save();populateFilters();render()}};
$('#exportBtn').onclick=()=>{const header=['acao','entrega','data','responsavel','status','prioridade','progresso'];const csv=[header.join(';'),...data.map(x=>[x.action,x.delivery,x.date,x.owner,x.status,x.priority,x.progress].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';'))].join('
');const blob=new Blob(['﻿'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plano-trabalho-2027.csv';a.click();URL.revokeObjectURL(a.href)};
$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const lines=r.result.replace(/^﻿/,'').split(/?
/).filter(Boolean);const split=l=>{let out=[],cur='',q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c==='"'&&l[i+1]==='"'){cur+='"';i++}else if(c==='"')q=!q;else if(c===';'&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out};const rows=lines.slice(1).map(split);data=rows.map((v,i)=>({id:Date.now()+'-'+i,action:v[0]||'',delivery:v[1]||'',date:v[2]||'2027-01-01',owner:v[3]||'',status:v[4]||'Planejada',priority:v[5]||'Média',progress:Number(v[6]||0)}));save();populateFilters();render();showToast('Base importada')};r.readAsText(file,'UTF-8')};
populateFilters();render();
